// Generated by ChatGPT

import {View, StyleSheet, StyleProp, ViewStyle} from 'react-native';
import React from 'react';

interface CircleProps {
  diameter: number;
  color: string;
}

const Circle: React.FC<CircleProps> = ({diameter, color}) => {
  // Define a style object with the specified diameter and color
  const circleStyle: StyleProp<ViewStyle> = {
    width: diameter,
    height: diameter,
    backgroundColor: color,
    borderRadius: diameter / 2, // Set border radius to make it a circle
  };

  return <View style={[styles.circle, circleStyle]} />;
};

const styles = StyleSheet.create({
  circle: {
    // You can add additional styles for the circle container here
  },
});

export default Circle;
