// Generated by ChatGPT

import {View, StyleSheet, StyleProp, ViewStyle} from 'react-native';
import React from 'react';

import useRandomColor from '../hooks/useRandomColor';
import useRandomSize from '../hooks/useRandomSize';

interface CircleProps {
  position: {
    x: number;
    y: number;
  };
}

const Circle: React.FC<CircleProps> = ({position}) => {
  const [color, toggleColor] = useRandomColor();
  const diameter = useRandomSize();
  // Define a style object with the specified diameter and color
  const circleStyle: StyleProp<ViewStyle> = {
    width: diameter,
    height: diameter,
    backgroundColor: color,
    borderRadius: diameter,
    position: 'absolute',
    left: position.x - diameter / 2,
    top: position.y - diameter / 2,
  };

  return <View style={[styles.circle, circleStyle]} />;
};

const styles = StyleSheet.create({
  circle: {
    // You can add additional styles for the circle container here
  },
});

export default Circle;
