// Generated by ChatGPT

import {Image, StyleProp, StyleSheet, ViewStyle} from 'react-native';
import React from 'react';

import useRandomPattern from '../hooks/useRandomPattern';
import useRandomSize from '../hooks/useRandomSize';

interface SquareProps {
  position: {
    x: number;
    y: number;
  };
}

const Square: React.FC<SquareProps> = ({position}) => {
  const [pattern, togglePattern] = useRandomPattern();
  const size = useRandomSize();

  // Define a style object with the specified size and color
  const squareStyle: StyleProp<ViewStyle> = {
    width: size,
    height: size,
    position: 'absolute',
    left: position.x - size / 2,
    top: position.y - size / 2,
  };

  return (
    <Image
      with={size}
      height={size}
      resizeMode="cover"
      source={{uri: pattern}}
      style={[styles.square, squareStyle]}
    />
  );
};

const styles = StyleSheet.create({
  square: {
    // You can add additional styles for the square container here
  },
});

export default Square;
