// Generated by ChatGPT

import React from 'react';
import {View, StyleSheet, StyleProp, ViewStyle} from 'react-native';

interface SquareProps {
  size: number;
  color: string;
}

const Square: React.FC<SquareProps> = ({size, color}) => {
  // Define a style object with the specified size and color
  const squareStyle: StyleProp<ViewStyle> = {
    width: size,
    height: size,
    backgroundColor: color,
  };

  return <View style={[styles.square, squareStyle]} />;
};

const styles = StyleSheet.create({
  square: {
    // You can add additional styles for the square container here
  },
});

export default Square;
