// Generated by ChatGPT

import {View, StyleSheet, StyleProp, ViewStyle} from 'react-native';
import React from 'react';

import useRandomColor from '../hooks/useRandomColor';
import useRandomSize from '../hooks/useRandomSize';

const Square: React.FC = () => {
  const color = useRandomColor();
  const size = useRandomSize();

  // Define a style object with the specified size and color
  const squareStyle: StyleProp<ViewStyle> = {
    width: size,
    height: size,
    backgroundColor: color,
  };

  return <View style={[styles.square, squareStyle]} />;
};

const styles = StyleSheet.create({
  square: {
    // You can add additional styles for the square container here
  },
});

export default Square;
