// Generated by ChatGPT

import React from 'react';

import useTriangleType from '../hooks/useTriangleType';

interface TriangleProps {
  position: {
    x: number;
    y: number;
  };
}

const Triangle: React.FC<TriangleProps> = ({position}) => {
  const TriangleType = useTriangleType();

  return <TriangleType position={position} />;
};

export default Triangle;
