// Generated by ChatGPT

import {View, StyleSheet, ViewStyle} from 'react-native';
import React from 'react';

interface TriangleProps {
  size: number;
  color: string;
}

const Triangle: React.FC<TriangleProps> = ({size, color}) => {
  // Define the triangle's border widths to create the triangle shape
  const borderStyles: ViewStyle = {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: size / 2,
    borderRightWidth: size / 2,
    borderBottomWidth: size,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: color,
  };

  return <View style={[styles.triangle, borderStyles]} />;
};

const styles = StyleSheet.create({
  triangle: {
    // You can add additional styles for the triangle container here
  },
});

export default Triangle;
